name: Story
description: Describe a user story to deliver value
title: "[Story]: "
labels: ["type: story"]
assignees: []
body:
  - type: textarea
    id: user_story
    attributes:
      label: User story
      description: Use the classic format
      placeholder: "As a <role>, I want <capability> so that <benefit>."
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance criteria
      description: Bullet list of testable outcomes
      placeholder: |
        - [ ] …
        - [ ] …
    validations:
      required: true

  - type: dropdown
    id: points
    attributes:
      label: Story points
      options: ["1","2","3","5","8","13","21"]
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: [P0, P1, P2, P3]
    validations:
      required: false

  - type: input
    id: sprint
    attributes:
      label: Sprint / Iteration (text)
      placeholder: e.g., 2025-W40 or Sprint 18
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Links, designs, or API references
    validations:
      required: false
