name: Task
description: Technical or operational task that produces a concrete deliverable
title: "[Task]: <Action + outcome>"
labels: ["type: task"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this for tech debt, infra work, scripts, config changes, docs, etc.

  - type: input
    id: parent
    attributes:
      label: Parent (Story or Epic)
      placeholder: https://github.com/org/repo/issues/123
    validations:
      required: false

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Action + outcome
      placeholder: "Automate log rotation to reduce disk usage"
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: Background
      placeholder: |
        Why this exists (tech debt, infra need, reliability, compliance) and any context.
    validations:
      required: false

  - type: textarea
    id: deliverables
    attributes:
      label: Deliverables
      description: Artifacts to produce
      placeholder: |
        - Script: rotate_logs.sh
        - Config: /etc/app/logrotate.conf
        - Doc: runbook update
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - CI passes
        - Runbook updated
        - New dashboard live at <link>
        - Approval from <owner>
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: [P0, P1, P2, P3]
    validations:
      required: false

  - type: textarea
    id: risks
    attributes:
      label: Risks (optional)
      placeholder: |
        Downtime window? Data loss possibilities? Mitigations/backout steps.
    validations:
      required: false

  - type: checkboxes
    id: quality_gates
    attributes:
      label: Quality gates (tick as complete)
      options:
        - label: Security/permissions reviewed (if applicable)
        - label: Monitoring updated
        - label: Docs/runbooks updated
        - label: Tests added or updated
